LearningAuth2/App1/urls.py
from django.urls import path
from App1 import views

app_name = 'App1'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login')
]

LearningAuth2/LearningAuth2/urls.py
from django.contrib import admin
from django.urls import path,include
from App1 import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index,name='index'),
    path('App1/',include('App1.urls')),
    path('logout',views.user_logout,name='logout')

]

LearningAuth2/App1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

    portfolio_site = models.URLField(blank=True)
    portfolio_pic = models.ImageField(blank=True,upload_to='profile_pics')

    def __str__(self):
        return self.user.username

LearningAuth2/App1/forms.py
from django import forms
from django.contrib.auth.models import User
from App1.models import UserProfileInfo

class User_Form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','portfolio_pic')

LearningAuth2/App1/views.py
from django.shortcuts import render
from App1.forms import User_Form,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'App1/index.html')

def register(request):
    registered  = False

    if request.method == "POST":
        user_form = User_Form(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'protfolio_pic' in request.FILES:
                profile.portfolio_pic = request.FILES['portfolio_pic']
            profile.save()
            registered = True
        
        else:
            print(user_form.errors,profile_form.errors)
    
    else:
        user_form = User_Form()
        profile_form = UserProfileInfoForm()


    return render(request,'App1/register.html',context={'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('The Account is no longer Active')
        else:
            return HttpResponse('No Account Found')
    return render(request,'App1/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

LearningAuth2/templates/App1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome To the Authorization Learning</h1>
    <h2>Click the Options Below</h2>
    <ol>
        <h4><a href="{% url 'index' %}">Index</a></h4>
        <h4><a href="{% url 'App1:register' %}">Register</a></h4>
        <h4><a href="{% url 'admin:index' %}">Admin</a></h4>

        
        {% if user.is_authenticated %}
            <h4><a href="{% url 'logout' %}">Logout</a></h4>
        {% else %}
            <h4><a href="{% url 'App1:login' %}">Login</a></h4>
        {% endif %}
            
    </ol>
    <hr>

    {% block body_block  %}

    {% endblock  %}
</body>
</html>

LearningAuth2/templates/App1/index.html
{% extends 'App1/base.html' %}

{% block body_block %}
<h1>Index Page</h1>
{% endblock  %}

LearningAuth2/templates/App1/login.html
{% extends 'App1/base.html' %}

{% block body_block %}
<h1>Login Page</h1>

<form action = {% url 'App1:login' %} method='POST'>
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Type your User Name">
    <label for="password">Password</label>
    <input type="text" name="password" placeholder="Password">
    <input type="submit" value="Login">
</form>

{% endblock  %}

LearningAuth2/templates/App1/register.html
{% extends 'App1/base.html' %}
{% load static %}

{% block body_block %}
<h1>Registration Page</h1>
<hr>

{% if registered %}
    <h3>Thank you for Registering</h3>

{% else %}
    <h3>Register Here</h3>
    <form enctype="multipart/form-data" method = "POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endif %}
    
{% endblock  %}